MODEL_PATH = "./fire.dxnn"

PORT = 5000
DEBUG = False

INPUT_SIZE = 640
CONF_THRES = 0.25
IOU_THRES = 0.45

PERSISTENCE_THRESHOLD = 10.0
GROWTH_FACTOR = 1.5

ALERT_SCRIPT = "./fire_alert.py"
ALERT_COOLDOWN = 30
